/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JObject */

#ifndef _Included_JObject
#define _Included_JObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JObject
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JObject_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
