/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JPrimitives */

#ifndef _Included_JPrimitives
#define _Included_JPrimitives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JPrimitives
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JPrimitives_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
