/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JString */

#ifndef _Included_JString
#define _Included_JString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JString
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JString_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
